import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import SmoothScrollProvider from '@/components/providers/SmoothScrollProvider'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="overflow-x-hidden">
			<SmoothScrollProvider>
				<body className={rubik.className}>
					<main className="bg-black overflow-x-hidden">
						{children}
					</main>
				</body>
			</SmoothScrollProvider>
		</html>
	)
}
